apiVersion: v1
kind: Namespace
metadata:
  name: gke-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: gke-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: gke-1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: gke-1
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
 name: nginx
 namespace: gke-1